import "server-only";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { PhotoDTO, PhotosListDTO } from "./types";

/**
 * Demo seed for previewing the wall WITHOUT a database or bucket.
 *
 * Only used when `KEEPSAKE_DEMO=1` and no `DATABASE_URL` is set (see
 * lib/photos.ts). Prefers real preview assets generated by
 * scripts/build-demo-assets.mjs (public/demo/manifest.json + images), shown in
 * their similarity order. Falls back to a handful of self-contained SVG
 * placeholders if those assets haven't been generated. Never active in
 * production with a real database.
 */

interface ManifestItem {
  n: string;
  w: number;
  h: number;
  takenAt: string | null;
}

const FALLBACK_ISO = "2026-07-12T00:00:00.000Z";

export async function demoAlbum(): Promise<PhotosListDTO> {
  try {
    const raw = await readFile(
      join(process.cwd(), "public", "demo", "manifest.json"),
      "utf8",
    );
    const items: ManifestItem[] = JSON.parse(raw);
    const photos: PhotoDTO[] = items.map((m) => ({
      id: `demo-${m.n}`,
      thumbUrl: `/demo/thumb/${m.n}.jpg`,
      width: m.w,
      height: m.h,
      caption: null,
      authorName: "the group",
      takenAt: m.takenAt,
      createdAt: m.takenAt ?? FALLBACK_ISO,
      altText: null,
      tags: null,
      hearts: 0,
      comments: 0,
      viewerReacted: false,
      viewerOwns: false,
    }));
    return { photos, viewer: { isContributor: false } };
  } catch {
    return sampleAlbum();
  }
}

// --- fallback: self-contained SVG placeholder wall (no assets needed) ---

interface Seed {
  w: number;
  h: number;
  caption: string | null;
  author: string;
  hearts: number;
  daysAgo: number;
  top: string;
  bot: string;
  orb: string;
  orbY: number;
}

const SEEDS: Seed[] = [
  { w: 1200, h: 820, caption: "low tide, before anyone woke up", author: "Mara", hearts: 5, daysAgo: 3, top: "#2b3f52", bot: "#d99b6a", orb: "#f2d7a8", orbY: 0.32 },
  { w: 900, h: 1200, caption: "he insisted on the hat", author: "Tomás", hearts: 8, daysAgo: 9, top: "#4a3428", bot: "#caa06a", orb: "#e9c79a", orbY: 0.28 },
  { w: 1000, h: 1000, caption: null, author: "Priya", hearts: 2, daysAgo: 14, top: "#39352e", bot: "#8f8672", orb: "#c7bda6", orbY: 0.4 },
  { w: 1200, h: 900, caption: "kitchen, 1am, third round of dumplings", author: "Mara", hearts: 11, daysAgo: 21, top: "#2a1e16", bot: "#b5722f", orb: "#eebd77", orbY: 0.22 },
  { w: 820, h: 1200, caption: "the long way home", author: "Jae", hearts: 3, daysAgo: 33, top: "#26304a", bot: "#b06a4a", orb: "#e2a884", orbY: 0.3 },
  { w: 1200, h: 800, caption: "found this roll in a drawer", author: "Tomás", hearts: 7, daysAgo: 52, top: "#4a4234", bot: "#cbb892", orb: "#e7dcbb", orbY: 0.36 },
];

const NOW = Date.parse("2026-07-12T18:00:00Z");
const DAY = 24 * 60 * 60 * 1000;

function svgThumb(s: Seed, i: number): string {
  const cx = i % 2 === 0 ? s.w * 0.68 : s.w * 0.3;
  const cy = s.h * s.orbY;
  const r = Math.min(s.w, s.h) * 0.16;
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='${s.w}' height='${s.h}'>
<defs><linearGradient id='g' x1='0' y1='0' x2='0' y2='1'>
<stop offset='0' stop-color='${s.top}'/><stop offset='1' stop-color='${s.bot}'/>
</linearGradient></defs>
<rect width='100%' height='100%' fill='url(#g)'/>
<circle cx='${cx.toFixed(0)}' cy='${cy.toFixed(0)}' r='${r.toFixed(0)}' fill='${s.orb}' opacity='0.55'/>
</svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

function sampleAlbum(): PhotosListDTO {
  const photos: PhotoDTO[] = SEEDS.map((s, i) => {
    const iso = new Date(NOW - s.daysAgo * DAY).toISOString();
    return {
      id: `demo-${i}-0000-0000-0000-000000000000`,
      thumbUrl: svgThumb(s, i),
      width: s.w,
      height: s.h,
      caption: s.caption,
      authorName: s.author,
      takenAt: iso,
      createdAt: iso,
      altText: null,
      tags: null,
      hearts: s.hearts,
      comments: 0,
      viewerReacted: false,
      viewerOwns: false,
    };
  });
  return { photos, viewer: { isContributor: false } };
}
